<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MProductChildCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $params = [
            ['parent_category_id' => 1, 'name' => '家の掃除'],
            ['parent_category_id' => 1, 'name' => '買物代行'],
            ['parent_category_id' => 1, 'name' => 'クリーニング'],
            ['parent_category_id' => 1, 'name' => '害虫駆除'],
            ['parent_category_id' => 1, 'name' => 'エアコン掃除'],
            ['parent_category_id' => 1, 'name' => '外壁掃除'],
            ['parent_category_id' => 1, 'name' => '運転代行'],
            ['parent_category_id' => 1, 'name' => '整理整頓'],
            ['parent_category_id' => 1, 'name' => '料理代行'],
            ['parent_category_id' => 1, 'name' => '洗濯'],
            ['parent_category_id' => 1, 'name' => '庭手入れ'],
            ['parent_category_id' => 2, 'name' => '水まわり'],
            ['parent_category_id' => 2, 'name' => '家電'],
            ['parent_category_id' => 2, 'name' => 'パソコン'],
            ['parent_category_id' => 2, 'name' => '自転車'],
            ['parent_category_id' => 2, 'name' => 'アクセサリー'],
            ['parent_category_id' => 2, 'name' => '家具'],
            ['parent_category_id' => 2, 'name' => '衣類'],
            ['parent_category_id' => 2, 'name' => 'スマホ'],
            ['parent_category_id' => 3, 'name' => 'ペットケア'],
            ['parent_category_id' => 3, 'name' => 'ペット理容'],
            ['parent_category_id' => 3, 'name' => 'しつけ'],
            ['parent_category_id' => 3, 'name' => 'ペットホテル'],
            ['parent_category_id' => 3, 'name' => 'ペット送迎'],
            ['parent_category_id' => 3, 'name' => '散歩'],
            ['parent_category_id' => 3, 'name' => 'ペット飼育代行'],
            ['parent_category_id' => 4, 'name' => '送迎'],
            ['parent_category_id' => 4, 'name' => '食事手伝い'],
            ['parent_category_id' => 4, 'name' => '高齢者のお世話'],
            ['parent_category_id' => 4, 'name' => '訪問理容'],
            ['parent_category_id' => 4, 'name' => 'デイサービス'],
            ['parent_category_id' => 5, 'name' => '送迎・運転代行'],
            ['parent_category_id' => 5, 'name' => '給油等代行'],
            ['parent_category_id' => 5, 'name' => '洗車等'],
            ['parent_category_id' => 6, 'name' => '引っ越し・運送'],
            ['parent_category_id' => 6, 'name' => '倉庫・トランクルーム'],
            ['parent_category_id' => 6, 'name' => '包装・梱包'],
            ['parent_category_id' => 7, 'name' => 'スポーツ・トレーニング'],
            ['parent_category_id' => 7, 'name' => '音楽'],
            ['parent_category_id' => 7, 'name' => '家庭教師'],
            ['parent_category_id' => 7, 'name' => '語学'],
            ['parent_category_id' => 7, 'name' => 'パソコン'],
            ['parent_category_id' => 7, 'name' => 'ガーデニング'],
            ['parent_category_id' => 7, 'name' => '武道'],
            ['parent_category_id' => 7, 'name' => '生花・華道'],
            ['parent_category_id' => 7, 'name' => 'ダンス'],
            ['parent_category_id' => 7, 'name' => '書道・そろばん'],
            ['parent_category_id' => 7, 'name' => 'ハンドメイド・手芸'],
            ['parent_category_id' => 7, 'name' => '資格'],
            ['parent_category_id' => 7, 'name' => '囲碁・将棋'],
            ['parent_category_id' => 7, 'name' => '茶道'],
            ['parent_category_id' => 7, 'name' => '占い代行'],
            ['parent_category_id' => 7, 'name' => '姓名判断等代行'],
            ['parent_category_id' => 7, 'name' => 'SNS 投稿代行'],
            ['parent_category_id' => 7, 'name' => '彼氏彼女代行'],
            ['parent_category_id' => 7, 'name' => 'e スポーツ'],
            ['parent_category_id' => 8, 'name' => 'ヘアデザイン・アレンジ'],
            ['parent_category_id' => 8, 'name' => '美容アドバイス'],
            ['parent_category_id' => 8, 'name' => 'メイクアップ'],
            ['parent_category_id' => 8, 'name' => 'ネイル・マツエク'],
            ['parent_category_id' => 8, 'name' => 'ダイエット'],
            ['parent_category_id' => 8, 'name' => 'コーディネート'],
            ['parent_category_id' => 9, 'name' => '写真撮影代行'],
            ['parent_category_id' => 9, 'name' => 'ビデオ撮影代行'],
            ['parent_category_id' => 9, 'name' => '画像・写真加工'],
            ['parent_category_id' => 9, 'name' => '撮影指導'],
            ['parent_category_id' => 10, 'name' => 'その他'],
            ['parent_category_id' => 10, 'name' => '不用品回収'],
            ['parent_category_id' => 10, 'name' => 'イベント'],
            ['parent_category_id' => 10, 'name' => '事務'],
            ['parent_category_id' => 10, 'name' => 'レンタル'],
            ['parent_category_id' => 10, 'name' => 'お墓参り'],
            ['parent_category_id' => 10, 'name' => '代行全般'],
            ['parent_category_id' => 10, 'name' => '補修、修理、造作'],
            ['parent_category_id' => 10, 'name' => '探偵依頼・調べもの'],
            ['parent_category_id' => 11, 'name' => 'インテリアデザイン'],
            ['parent_category_id' => 11, 'name' => 'インテリアアドバイス'],
            ['parent_category_id' => 11, 'name' => 'ガーデニング'],
            ['parent_category_id' => 11, 'name' => '野外インテリア'],
            ['parent_category_id' => 11, 'name' => 'オフィスインテリア'],
            ['parent_category_id' => 11, 'name' => '店舗インテリア'],
            ['parent_category_id' => 11, 'name' => 'SNS 向けインテリア'],
            ['parent_category_id' => 11, 'name' => 'アート・絵画'],
            ['parent_category_id' => 11, 'name' => '収納アドバイス'],
            ['parent_category_id' => 11, 'name' => 'ホームオフィスインテリア'],
            ['parent_category_id' => 11, 'name' => '壁紙・塗装'],
            ['parent_category_id' => 11, 'name' => '観葉植物'],
            ['parent_category_id' => 12, 'name' => 'ロゴ'],
            ['parent_category_id' => 12, 'name' => 'チラシ・DM'],
            ['parent_category_id' => 12, 'name' => '名刺'],
            ['parent_category_id' => 12, 'name' => 'メニュー表'],
            ['parent_category_id' => 12, 'name' => 'ポスター'],
            ['parent_category_id' => 12, 'name' => 'カタログ'],
            ['parent_category_id' => 12, 'name' => 'その他デザイン'],
            ['parent_category_id' => 13, 'name' => 'パソコン入力'],
            ['parent_category_id' => 13, 'name' => '機材設置代行'],
            ['parent_category_id' => 13, 'name' => '資料作成代行'],
            ['parent_category_id' => 13, 'name' => '印刷'],
            ['parent_category_id' => 13, 'name' => 'デザイン代行'],
            ['parent_category_id' => 13, 'name' => 'プログラミング'],
            ['parent_category_id' => 13, 'name' => 'ホームページ'],
            ['parent_category_id' => 13, 'name' => 'バナーデザイン'],
            ['parent_category_id' => 13, 'name' => 'HTML・CSSコーディング'],
            ['parent_category_id' => 13, 'name' => 'その他'],
            ['parent_category_id' => 14, 'name' => '資料・企画書作成'],
            ['parent_category_id' => 14, 'name' => 'データ入力・文字起こし'],
            ['parent_category_id' => 14, 'name' => '事業計画作成サポート'],
            ['parent_category_id' => 14, 'name' => 'データ整理・Excel'],
            ['parent_category_id' => 14, 'name' => 'コンサルティング'],
            ['parent_category_id' => 14, 'name' => '各書類作成・給与計算'],
            ['parent_category_id' => 14, 'name' => '秘書・アシスタント'],
            ['parent_category_id' => 14, 'name' => '起業・独立'],
            ['parent_category_id' => 14, 'name' => 'その他'],
            ['parent_category_id' => 15, 'name' => 'お墓参り'],
            ['parent_category_id' => 15, 'name' => 'お墓掃除'],
            ['parent_category_id' => 15, 'name' => '神仏手続き'],
            ['parent_category_id' => 15, 'name' => '結婚式'],
            ['parent_category_id' => 15, 'name' => '結婚式撮影'],
            ['parent_category_id' => 15, 'name' => '送迎サービス'],
            ['parent_category_id' => 15, 'name' => '代理出席'],
            ['parent_category_id' => 15, 'name' => 'その他'],
            ['parent_category_id' => 16, 'name' => '料理代行・出張料理'],
            ['parent_category_id' => 16, 'name' => '料理教室'],
            ['parent_category_id' => 16, 'name' => 'テイクアウト配達代行'],
            ['parent_category_id' => 16, 'name' => 'お弁当'],
            ['parent_category_id' => 16, 'name' => '飲食コンサルティング'],
            ['parent_category_id' => 17, 'name' => '恋愛相談'],
            ['parent_category_id' => 17, 'name' => 'モテる方法アドバイス'],
            ['parent_category_id' => 17, 'name' => '浮気・不倫相談'],
            ['parent_category_id' => 17, 'name' => '婚活相談'],
            ['parent_category_id' => 17, 'name' => '結婚式の相談'],
            ['parent_category_id' => 17, 'name' => '恋愛マッチングアプリ代行'],
            ['parent_category_id' => 18, 'name' => 'スポーツ・アウトドア'],
            ['parent_category_id' => 18, 'name' => 'ウエルネス・健康'],
            ['parent_category_id' => 18, 'name' => '料理教室'],
            ['parent_category_id' => 18, 'name' => '旅行・観光ツアー'],
            ['parent_category_id' => 18, 'name' => '趣味・カルチャー'],
            ['parent_category_id' => 19, 'name' => 'シェフ・ケータリング'],
            ['parent_category_id' => 19, 'name' => 'イベント司会'],
            ['parent_category_id' => 19, 'name' => 'ネイル'],
            ['parent_category_id' => 19, 'name' => 'DJ・演奏'],
            ['parent_category_id' => 19, 'name' => 'マジシャン・パフォーマー'],
            ['parent_category_id' => 19, 'name' => 'ヘアメイク・着付け'],
            ['parent_category_id' => 19, 'name' => '家事代行'],
            ['parent_category_id' => 19, 'name' => 'スポーツ助っ人'],
            ['parent_category_id' => 19, 'name' => 'その他出張サービス'],
            ['parent_category_id' => 20, 'name' => '物件、土地検索代行'],
            ['parent_category_id' => 20, 'name' => '探偵依頼'],
            ['parent_category_id' => 20, 'name' => '調べもの代行'],
            ['parent_category_id' => 20, 'name' => 'その他'],
            ['parent_category_id' => 21, 'name' => '民泊'],
            ['parent_category_id' => 21, 'name' => '自動車'],
            ['parent_category_id' => 21, 'name' => 'バイク'],
            ['parent_category_id' => 21, 'name' => '自転車'],
            ['parent_category_id' => 21, 'name' => '船'],
            ['parent_category_id' => 21, 'name' => '工具'],
            ['parent_category_id' => 21, 'name' => 'オフィス'],
            ['parent_category_id' => 21, 'name' => 'イベント機材'],
            ['parent_category_id' => 21, 'name' => 'アウトドア用品'],
            ['parent_category_id' => 21, 'name' => '料理人(ケータリング)'],
            ['parent_category_id' => 21, 'name' => '人材派遣'],
        ];
        \DB::table('m_product_child_categories')->insert($params);
    }
}
